language: generic
sudo: required

branches:
  only:
    - master

env:
  global:
    - PATH=${TRAVIS_BUILD_DIR/bats/bin}:${PATH}

addons:
  apt:
    packages:
      - bash

services:
  - docker

before_install:
  - sudo chmod +x build.sh
  - sudo chmod +x test.sh
  - sudo chmod +x push_docker_images.sh

before_script:
  - ./build.sh

script:
  - ./test.sh

after_success:
  - ./push_docker_images.sh
